name: pyML
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - crc32c=2.7.1=py311hb76fab6_2
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.0=py311ha891d26_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - filelock=3.13.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.10=h27ca646_0
  - fsspec=2024.2.0=pyhca7485f_0
  - gdk-pixbuf=2.44.3=h7542897_0
  - gettext=0.21.1=h0186832_0
  - glslang=16.0.0=h60b4770_0
  - gmp=6.3.0=h965bd2d_0
  - gmpy2=2.1.2=py311h2ba9262_1
  - gnutls=3.7.9=hd26332c_0
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=12.1.0=haf38c7b_0
  - hdf5=1.14.6=nompi_he65715a_103
  - icu=75.1=hfee45f7_0
  - idna=3.6=pyhd8ed1ab_0
  - imath=3.2.2=h3470cca_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.0=pyh3cd1d5f_0
  - ipython=8.20.0=pyh707e725_0
  - jasper=4.2.8=hc0e5025_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py311h267d04e_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=20_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.2=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=h1bb475b_0
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libidn2=2.3.4=h1a8c8d9_0
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h7274d02_4
  - liblapack=3.9.0=20_osxarm64_openblas
  - liblapacke=3.9.0=20_osxarm64_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libopencv=4.12.0=headless_py311h109a709_7
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h702a38d_1
  - librsvg=2.60.0=h5c55ec3_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.7.1=h7dc4979_0
  - libunistring=0.9.10=h3422bc3_0
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.15.0=h9329255_1
  - libxml2-16=2.15.0=h0ff4647_1
  - libzlib=1.3.1=h8359307_2
  - lightning=2.2.0.post0=pyhd8ed1ab_0
  - lightning-utilities=0.10.1=pyhd8ed1ab_0
  - llvm-openmp=17.0.6=hcd81f8e_0
  - markupsafe=2.1.3=py311heffc1b2_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h9546428_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.1.1=py311h57a9ea7_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.5.9=pyhd8ed1ab_0
  - nettle=3.9.1=h40ed0f5_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - numcodecs=0.16.1=py311hff7e5bb_1
  - numpy=1.26.3=py311h7125741_0
  - opencv=4.12.0=headless_py311h704ec6c_7
  - openexr=3.4.1=h6aeeebb_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openjph=0.24.1=h23bdaea_0
  - openssl=3.5.4=h5503f6c_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.2=pyhd8ed1ab_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311h8dc27b9_2
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py311h05b510d_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.12.0=headless_py311h1b9f5d6_7
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.14=hec0b533_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytorch=2.1.2=py3.11_0
  - pytorch-lightning=2.1.3=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=25.1.2=py311h6727e71_0
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h92ec313_1
  - requests=2.31.0=pyhd8ed1ab_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.24=h919df07_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - shaderc=2025.4=h1a5098f_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.2=hd121638_0
  - spirv-tools=2025.4=ha7d2532_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2022.2.0=h5b2e6d4_1
  - tk=8.6.13=h5083fa2_1
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - torchvision=0.16.2=py311_cpu
  - tornado=6.3.3=py311heffc1b2_1
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - tzdata=2023d=h0c530f3_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - wrapt=1.17.3=py311h3696347_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - yaml=0.2.5=h3422bc3_2
  - zarr=3.1.3=pyhcf101f3_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aiobotocore==2.24.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - blis==0.7.11
      - botocore==1.40.18
      - catalogue==2.0.10
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==3.1.1
      - confection==0.1.4
      - coverage==7.11.0
      - cymem==2.0.8
      - czifile==2019.7.2.1
      - dask==2025.9.1
      - en-core-web-sm==3.7.1
      - imageio==2.36.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jmespath==1.0.1
      - langcodes==3.3.0
      - lazy-loader==0.4
      - locket==1.0.0
      - monai==1.4.0
      - murmurhash==1.0.10
      - nd2==0.10.3
      - nibabel==5.3.2
      - nltk==3.8.1
      - ome-types==0.6.1
      - ome-zarr==0.12.2
      - opencv-rolling-ball==1.0.1
      - partd==1.4.2
      - pluggy==1.6.0
      - preshed==3.0.9
      - propcache==0.3.2
      - pycore==17.4.17
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pydicom==3.0.1
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - python-graphviz==0.20.3
      - regex==2023.12.25
      - resource-backed-dask-array==0.1.0
      - s3fs==2023.12.2
      - safetensors==0.4.2
      - scikit-image==0.24.0
      - sentence-transformers==2.3.1
      - sentencepiece==0.1.99
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.3
      - tifffile==2024.9.20
      - toolz==1.0.0
      - torchviz==0.0.2
      - torchxrayvision==1.2.4
      - transformers==4.37.2
      - typer==0.9.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - wasabi==1.1.2
      - weasel==0.3.4
      - xsdata==24.3.1
      - yarl==1.20.1
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/pyML
