name: pyML
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - ca-certificates
  - openssl
  - pytorch
  - torchvision
  - ipykernel
  - lightning
  - certifi
  - zarr
  - opencv
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/pyML
